homeassistant:
  auth_providers:
    - type: homeassistant
    # Uncomment next line if you want to enable legacy API password support
    # - type: legacy_api_password
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
#  whitelist_external_dirs:
#    - /ssl

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem
  #trusted_networks:
  #  - !secret home_network
  #  - !secret ha_network
  #  - !secret vpn_network

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:
#  google_actions:

group: !include groups.yaml
automation: !include_dir_list automations/
script: !include_dir_list scripts/

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass

wemo:
  static:
    - !secret heidinightstandip

zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 4500
  icon: mdi:home

notify: !include notifications.yaml

homekit:
  auto_start: False
  filter:
    exclude_domains:
      device_tracker

switch: !include switches.yaml

zeroconf:

camera: !include cameras.yaml

light:
  - platform: group
    name: Boy's Room
    entities:
      - light.hue_white_lamp_1
      - light.hue_white_lamp_2

logger:
  default: error

climate:

recorder:
  purge_keep_days: 30

history:

tplink:
  switch:
    - host: !secret shaun_nightstand_ip

system_health:

downloader:
  download_dir: downloads

ffmpeg:

api:

input_datetime:
  climate_night:
    has_time: true
  climate_morning:
    has_time: true

input_number:
  ac_set_point_home_day:
    name: "AC Set Point Home Day"
    mode: box
    initial: 73
    min: 60
    max: 80
    step: 1
  ac_set_point_away_day:
    name: "AC Set Point Away Day"
    mode: box
    initial: 76
    min: 60
    max: 80
    step: 1
  ac_set_point_home_night:
    name: "AC Set Point Home Night"
    mode: box
    initial: 75
    min: 60
    max: 80
    step: 1
  ac_set_point_away_night:
    name: "AC Set Point Away Night"
    mode: box
    initial: 78
    min: 60
    max: 80
    step: 1
  heat_set_point_home_day:
    name: "Heat Set Point Home Day"
    mode: box
    initial: 71
    min: 60
    max: 80
    step: 1
  heat_set_point_away_day:
    name: "Heat Set Point Away Day"
    mode: box
    initial: 68
    min: 60
    max: 80
    step: 1
  heat_set_point_home_night:
    name: "Heat Set Point Home Night"
    mode: box
    initial: 69
    min: 60
    max: 80
    step: 1
  heat_set_point_away_night:
    name: "Heat Set Point Away Night"
    mode: box
    initial: 66
    min: 60
    max: 80
    step: 1
  auto_low_set_point_home_day:
    name: "Auto Low Set Point Home Day"
    mode: box
    initial: 71
    min: 60
    max: 80
    step: 1
  auto_low_set_point_away_day:
    name: "Auto Low Set Point Away Day"
    mode: box
    initial: 68
    min: 60
    max: 80
    step: 1
  auto_high_set_point_home_day:
    name: "Auto High Set Point Home Day"
    mode: box
    initial: 73
    min: 60
    max: 80
    step: 1
  auto_high_set_point_away_day:
    name: "Auto High Set Point Away Day"
    mode: box
    initial: 76
    min: 60
    max: 80
    step: 1
  auto_low_set_point_home_night:
    name: "Auto Low Set Point Home Night"
    mode: box
    initial: 69
    min: 60
    max: 80
    step: 1
  auto_low_set_point_away_night:
    name: "Auto Low Set Point Away Night"
    mode: box
    initial: 66
    min: 60
    max: 80
    step: 1
  auto_high_set_point_home_night:
    name: "Auto High Set Point Home Night"
    mode: box
    initial: 75
    min: 60
    max: 80
    step: 1
  auto_high_set_point_away_night:
    name: "Auto High Set Point Away Night"
    mode: box
    initial: 78
    min: 60
    max: 80
    step: 1

ios:
