
- platform: mqtt
  name: boysroomtemp
  state_topic: "tele/boysroom/SENSOR"
  value_template: "{{ value_json['AM2301'].Temperature }}"
  unit_of_measurement: "°F"
- platform: mqtt
  name: boysroomhumidity
  state_topic: "tele/boysroom/SENSOR"
  value_template: "{{ value_json['AM2301'].Humidity }}"
  unit_of_measurement: "%"
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
    - 'beat'
- platform: uptime
  unit_of_measurement: hours
- platform: cert_expiry
  host: !secret cert_url
  port: 443
- platform: template
  sensors:
    hvac_set_temp:
      friendly_name: "HVAC Set Temp"
      value_template: "{{ states.climate.radio_thermostat_company_of_america_ct101_thermostat_mode.attributes.temperature|float }}"
    hvac_set_temp_low:
      friendly_name: "HVAC Set Temp Low"
      value_template: "{{ states.climate.radio_thermostat_company_of_america_ct101_thermostat_mode.attributes.target_temp_low|float }}"
    hvac_set_temp_high:
      friendly_name: "HVAC Set Temp High"
      value_template: "{{ states.climate.radio_thermostat_company_of_america_ct101_thermostat_mode.attributes.target_temp_high|float }}"
    hvac_mode:
      friendly_name: "HVAC Mode"
      value_template: "{{ states('climate.radio_thermostat_company_of_america_ct101_thermostat_mode') }}"
    living_room_temp:
      friendly_name: "Living room temperature"
      unit_of_measurement: "°F"
      value_template: "{{ states('sensor.radio_thermostat_company_of_america_ct101_thermostat_temperature') }}"
    living_room_humidity:
      friendly_name: "Living room humidity"
      unit_of_measurement: "%"
      value_template: "{{ states('sensor.radio_thermostat_company_of_america_ct101_thermostat_relative_humidity') }}"
    heat_home_temp_to_use:
      friendly_name: "Heat home temp to Use"
      entity_id: sensor.time
      unit_of_measurement: 'degrees'
      value_template: >-
        {% set ftime = states('sensor.time')|replace(':', '.')|float %}
        {% if ftime >= 7.30 and ftime < 22.00 %}
          {{ states('input_number.heat_set_point_home_day') }}
        {% else %}
          {{ states('input_number.heat_set_point_home_night') }}
        {% endif %}
    ac_home_temp_to_use:
      friendly_name: "AC home temp to Use"
      entity_id: sensor.time
      unit_of_measurement: 'degrees'
      value_template: >-
        {% set ftime = states('sensor.time')|replace(':', '.')|float %}
        {% if ftime >= 7.30 and ftime < 22.00 %}
          {{ states('input_number.ac_set_point_home_day') }}
        {% else %}
          {{ states('input_number.ac_set_point_home_night') }}
        {% endif %}
    auto_ac_home_temp_to_use:
      friendly_name: "Auto AC home temp to Use"
      entity_id: sensor.time
      unit_of_measurement: 'degrees'
      value_template: >-
        {% set ftime = states('sensor.time')|replace(':', '.')|float %}
        {% if ftime >= 7.30 and ftime < 22.00 %}
          {{ states('input_number.auto_high_set_point_home_day') }}
        {% else %}
          {{ states('input_number.auto_high_set_point_home_night') }}
        {% endif %}
    auto_heat_home_temp_to_use:
      friendly_name: "Auto heat home temp to Use"
      entity_id: sensor.time
      unit_of_measurement: 'degrees'
      value_template: >-
        {% set ftime = states('sensor.time')|replace(':', '.')|float %}
        {% if ftime >= 7.30 and ftime < 22.00 %}
          {{ states('input_number.auto_low_set_point_home_day') }}
        {% else %}
          {{ states('input_number.auto_low_set_point_home_night') }}
        {% endif %}
    heat_away_temp_to_use:
      friendly_name: "Heat away temp to Use"
      entity_id: sensor.time
      unit_of_measurement: 'degrees'
      value_template: >-
        {% set ftime = states('sensor.time')|replace(':', '.')|float %}
        {% if ftime >= 7.30 and ftime < 22.00 %}
          {{ states('input_number.heat_set_point_away_day') }}
        {% else %}
          {{ states('input_number.heat_set_point_away_night') }}
        {% endif %}
    ac_away_temp_to_use:
      friendly_name: "AC away temp to Use"
      entity_id: sensor.time
      unit_of_measurement: 'degrees'
      value_template: >-
        {% set ftime = states('sensor.time')|replace(':', '.')|float %}
        {% if ftime >= 7.30 and ftime < 22.00 %}
          {{ states('input_number.ac_set_point_away_day') }}
        {% else %}
          {{ states('input_number.ac_set_point_away_night') }}
        {% endif %}
    auto_ac_away_temp_to_use:
      friendly_name: "Auto AC away temp to Use"
      entity_id: sensor.time
      unit_of_measurement: 'degrees'
      value_template: >-
        {% set ftime = states('sensor.time')|replace(':', '.')|float %}
        {% if ftime >= 7.30 and ftime < 22.00 %}
          {{ states('input_number.auto_high_set_point_away_day') }}
        {% else %}
          {{ states('input_number.auto_high_set_point_away_night') }}
        {% endif %}
    auto_heat_away_temp_to_use:
      friendly_name: "Auto heat away temp to Use"
      entity_id: sensor.time
      unit_of_measurement: 'degrees'
      value_template: >-
        {% set ftime = states('sensor.time')|replace(':', '.')|float %}
        {% if ftime >= 7.30 and ftime < 22.00 %}
          {{ states('input_number.auto_low_set_point_away_day') }}
        {% else %}
          {{ states('input_number.auto_low_set_point_away_night') }}
        {% endif %}
- platform: openweathermap
  api_key: !secret openweathermap_api_key
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - clouds
    - rain
    - snow
    - weather_code
- platform: tautulli
  api_key: !secret tautulli_api_key
  host: !secret tautulli_host
