
- platform: mqtt
  name: boysroomtemp
  state_topic: "tele/boysroom/SENSOR"
  value_template: "{{ value_json['AM2301'].Temperature }}"
  unit_of_measurement: "°F"
- platform: mqtt
  name: boysroomhumidity
  state_topic: "tele/boysroom/SENSOR"
  value_template: "{{ value_json['AM2301'].Humidity }}"
  unit_of_measurement: "%"
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
    - 'beat'
- platform: uptime
  unit_of_measurement: hours
- platform: cert_expiry
  host: !secret cert_url
  port: 443
- platform: template
  sensors:
    living_room_temp:
      friendly_name: "Living room temperature"
      unit_of_measurement: "°F"
      value_template: "{{ states.climate.radio_thermostat_company_of_america_ct101_thermostat_cooling_1.attributes.current_temperature }}"
    hvac_mode:
      friendly_name: "HVAC Mode"
      value_template: "{{ states.climate.radio_thermostat_company_of_america_ct101_thermostat_cooling_1.attributes.hvac_action }}"
- platform: ring
- platform: openweathermap
  api_key: !secret openweathermap_api_key
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - clouds
    - rain
    - snow
    - weather_code
