- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
# Axe Effect
- platform: snmp
  host: 172.16.6.27
  community: mccloud
  baseoid: 1.3.6.1.2.1.99.1.1.1.4.0
  device_class: Temperature
  name: AXE1
  unit_of_measurement: "°F"
  unique_id: 1234.0
  value_template: "{{((value | float) / 100 * 1.8 + 32) | float | round(2)}}"
  version: 2c
- platform: snmp
  host: 172.16.6.27
  community: mccloud
  baseoid: 1.3.6.1.2.1.99.1.1.2.4.0
  device_class: Humidity
  name: AXE1
  unit_of_measurement: "%"
  unique_id: 1234.1
  value_template: "{{((value | float) / 1000) | float | round(2)}}"
  version: 2c
