alias: AC Set Home
initial_state: True
trigger:
  platform: state
  entity_id: group.thermostatdevices
  from: 'not_home'
  to: 'home'
condition:
  - condition: state
    entity_id: climate.sensi
    state: cool
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.sensi
      temperature: >-
        {{ state_attr('climate.sensi', 'temperature')|int(73) - 3 }}
  - service: notify.pushbullet
    data:
      title: 'Thermostat set temp changed due to devices getting home'
      message: ''
