alias: Auto Set Away
initial_state: True
trigger:
  platform: state
  entity_id: group.thermostatdevices
  from: 'home'
  to: 'not_home'
condition:
  - condition: state
    entity_id: climate.sensi
    state: auto
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.sensi
      temperature: 72
      target_temp_low: >-
        {{ states('input_text.auto_low_set_point_away')|int }}
      target_temp_high: >-
        {{ states('input_text.auto_high_set_point_away')|int }}
  - service: notify.pushbullet
    data:
      title: 'Thermostat set temp changed due to devices leaving home'
      message: ''
