alias: Bedtime
initial_state: True
trigger:
  platform: time
  at: '18:30:00'
condition:
  condition: state 
  entity_id: 'group.bedtimephones'
  state: 'home'
action:
  - service: switch.turn_on
    entity_id: switch.heidi_nightstand
  - service: switch.turn_on
    entity_id: switch.boys_lamp
  - service: light.turn_on
    data:
      entity_id: light.boys_room_2
#      brightness_pct: 1
      brightness_pct: 'input_number.boys_room_limited_brightness'
  - service: climate.set_fan_mode
    data:
      entity_id: climate.sensi
      fan_mode: 'On'
  - service: notify.pushbullet
    data:
      message: "Furnace fan, Heidi's nightstand & boy's lamp turned on"
      title: "Bedtime"
