alias: Bedtime
initial_state: True
trigger:
  platform: time
  at: '18:45:00'
condition:
  condition: state 
  entity_id: 'group.bedtimephones'
  state: 'home'
action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Boy's Room"
      scene_name: Test
  - service: notify.pushbullet
    data:
      message: "Boy's ceiling lights turned on"
      title: "Bedtime"
