alias: Bedtime
initial_state: True
trigger:
  platform: time
  at: '18:45:00'
condition:
  condition: state 
  entity_id: 'group.bedtimephones'
  state: 'home'
action:
  - service: light.turn_on
    data:
      entity_id: light.boy_s_room
      brightness_pct: 10
  - service: notify.mobile_app_Shaun_iPhone
    data:
      title: "Bedtime"
      message: "Boy's room light turned on"
