alias: "Bedtime Boy's Room"
initial_state: True
trigger:
  platform: time
  at: input_datetime.bedtime
condition:
  condition: state
  entity_id: 'group.bedtimephones'
  state: 'home'
action:
  - service: light.turn_on
    data:
      entity_id: light.boy_s_room
      brightness_pct: 10
