# check if furnace filter change time
alias: 'Check furnace filter change date'
trigger:
  platform: sun
  # Possible values: sunset, sunrise
  event: sunrise
  # Optional time offset. +/-HH:MM:SS offset: '+00:03:00'
condition:
  condition: template
  value_template: '{{ states.sensor.date.state >= states.sensor.furnacefilter.state }}'
action:
- service: persistent_notification.create
  data:
    message: "Furnace Filter"
    title: "Time to change furnace filter"
- service: notify.gmail
  data:
    title: "Furnace Filter"
    message: "Time to change furnace filter"
- service: notify.pushbullet
  data:
    title: "Furnace Filter"
    message: "Time to change furnace filter"
