alias: CT101 Temp Set
initial_state: False
trigger:
  platform: time_pattern
  minutes: "/1"
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_mode
      state: heat
    - condition: state
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_mode
      state: cool
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_mode
      temperature: >-
        {% if is_state('sensor.hvac_mode', 'heat') -%}
          {% if states('sensor.heat_home_temp_to_use')|float != states('sensor.hvac_set_temp')|float -%}
            {{ states('sensor.heat_home_temp_to_use')|float }}
          {%- endif %}
        {% elif is_state('sensor.hvac_mode', 'cool') %}
          {% if states('sensor.ac_home_temp_to_use')|float != states('sensor.hvac_set_temp')|float -%}
            {{ states('sensor.ac_home_temp_to_use')|float }}
          {%- endif %}
        {%- endif %}
