alias: CT101 Temp Set
initial_state: False
trigger:
  platform: time_pattern
  minutes: "/5"
action:
  - service: climate.set_temperature
    data_template:
      entity_id: all
      temperature: >-
        {% if is_state('sensor.hvac_mode', 'heat') -%}
          {% if states('sensor.heat_home_temp_to_use')|float != states('sensor.hvac_set_temp')|float -%}
            sensor.heat_home_temp_to_use|float
          {%- endif %}
        {% elif is_state('sensor.hvac_mode', 'cool') %}
          {% if states('sensor.ac_home_temp_to_use')|float != states('sensor.hvac_set_temp')|float -%}
            sensor.ac_home_temp_to_use|float
          {%- endif %}
        {% elif is_state('sensor.hvac_mode', 'heat_cool') %}
          {% if states('sensor.auto_ac_home_temp_to_use')|float != states('sensor.hvac_set_temp_low')|float or states('sensor.auto_heat_home_temp_to_use')|float != states('sensor.hvac_set_temp_high')|float -%}
            #sensor.auto_ac_home_temp_to_use
            #sensor.auto_heat_home_temp_to_use
          {%- endif %}
        {%- endif %}
