alias: Auto Set Night
initial_state: True
trigger:
  platform: time
  at: '22:00:00'
condition:
  - condition: state
    entity_id: climate.z_wave_thermostat
    state: heat_cool
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.z_wave_thermostat
      target_temp_low: >
        {% if is_state('group.thermostatdevices', 'home') %}
          {{ states('input_number.auto_low_set_point_home_night') }}
        {% else %}
          {{ states('input_number.auto_low_set_point_away_night') }}
        {% endif %}
  - service: climate.set_temperature
    data_template:
      entity_id: climate.z_wave_thermostat
      target_temp_high: >
        {% if is_state('group.thermostatdevices', 'home') %}
          {{ states('input_number.auto_high_set_point_home_night') }}
        {% else %}
          {{ states('input_number.auto_high_set_point_away_night') }}
        {% endif %}
  - service: notify.mobile_app_Shaun_iPhone
    data:
      title: "Night time"
      message: "Setting target temps for the night"
