alias: CT101 Heat Set Morning
initial_state: True
trigger:
  platform: time
  at: '08:00:00'
condition:
  - condition: state
    entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_cooling_1
    state: heat
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_cooling_1
      temperature: >-
        {{ state_attr('climate.radio_thermostat_company_of_america_ct101_thermostat_cooling_1', 'temperature')|int(71) + 2 }}
  - service: notify.pushbullet
    data:
      title: 'CT101 thermostat set temp changed due to morning'
      message: ''
