alias: CT101 AC Set
initial_state: False
trigger:
    platform: time_pattern
    minutes: "/15"
condition:
  - condition: state
    entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_cooling_1
    state: cool
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_cooling_1
      temperature: >-
        {{ state_attr('climate.climate.radio_thermostat_company_of_america_ct101_thermostat_cooling_1', 'temperature')|int(73) + 3 }}
  - service: notify.pushbullet
    data:
      title: 'CT101 thermostat set temp changed due to devices leaving home'
      message: ''
