alias: CT101 AC Set Morning
initial_state: True
trigger:
  platform: time
  at: '07:30:00'
condition:
  - condition: state
    entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_mode
    state: cool
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_mode
      temperature: >-
        {{ state_attr('climate.radio_thermostat_company_of_america_ct101_thermostat_mode', 'temperature')|int(73) - 2 }}
