alias: Heat Set Night
initial_state: True
trigger:
  platform: time
  at: '22:00:00'
condition:
  - condition: state
    entity_id: climate.z_wave_thermostat
    state: heat
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.z_wave_thermostat
      temperature: >
        {% if is_state('group.thermostatdevices', 'home') %}
          {{ states('input_number.heat_set_point_home_night') }}
        {% else %}
          {{ states('input_number.heat_set_point_away_night') }}
        {% endif %}
  - service: notify.mobile_app_Shaun_iPhone
    data:
      title: "Night time"
      message: "Lowering temp for night time"
