alias: CT101 Set Auto
initial_state: True
trigger:
  platform: state
  entity_id: climate.sensi
  to: 'auto'
action:
  - service: climate.set_hvac_mode
    entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_cooling_1
    data:
      hvac_mode: heat_cool
  - service: climate.set_hvac_mode
    entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_heating_1
    data:
      hvac_mode: heat_cool
  - service: notify.pushbullet
    data:
      title: 'CT101 mode sync'
      message: ''
