alias: CT101 Auto Set Home
initial_state: True
trigger:
  platform: state
  entity_id: group.thermostatdevices
  from: 'not_home'
  to: 'home'
condition:
  - condition: state
    entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_cooling_1
    state: heat_cool
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_cooling_1
      temperature: >-
        {{ state_attr('climate.radio_thermostat_company_of_america_ct101_thermostat_cooling_1', 'target_temp_low')|int(71) + 3 }}
  - service: climate.set_temperature
    data_template:
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_heating_1
      target_temp_high: >-
        {{ state_attr('climate.radio_thermostat_company_of_america_ct101_thermostat_heating_1', 'target_temp_high')|int(73) - 3 }}
  - service: notify.pushbullet
    data:
      title: 'CT101 thermostat set temp changed due to devices getting home'
      message: ''
