alias: CT101 Heat Set Night
initial_state: True
trigger:
  platform: time
  at: '22:00:00'
condition:
  - condition: state
    entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_mode
    state: heat
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.radio_thermostat_company_of_america_ct101_thermostat_mode
      temperature: "{{ states('input_number.heat_set_point_home_night') }}"
  - service: notify.mobile_app_Shaun_iPhone
    data:
      title: "Nighttime"
      message: "Lowering temp for night time"
