alias: AC Set Morning
initial_state: True
trigger:
  platform: time
  at: '07:30:00'
condition:
  - condition: state
    entity_id: climate.z_wave_thermostat
    state: cool
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.z_wave_thermostat
      temperature: >
        {% if is_state('group.thermostatdevices', 'home') %}
          {{ states('input_number.ac_set_point_home_day') }}
        {% else %}
          {{ states('input_number.ac_set_point_away_day') }}
        {% endif %}
  - service: notify.mobile_app_Shaun_iPhone
    data:
      title: "Morning"
      message: "Lowering temp for the day"
