alias: 'Downstairs Hallway'
initial_state: true
triggers:
  - trigger: mqtt
    topic: "zigbee2mqtt/Aqara Button 1/action"
    payload: "single"
  - trigger: mqtt
    topic: "zigbee2mqtt/Aqara Button 2/action"
    payload: "single"
action:
  - service: light.toggle
    data:
      entity_id: light.downstairs_hallway
