alias: Downstairs Hallway Reset
initial_state: True
trigger:
  platform: state
  entity_id: light.downstairs_hallway
  from:
    - "unknown"
    - "unavailable"
  to: "on"
condition:
  - condition: time
    after: "07:00:00"
    before: "19:45:00"
  - condition: template # run only once every 15 minutes
    value_template: "{{ ( as_timestamp(now()) - as_timestamp(state_attr('automation.downstairs_hallway_resett', 'last_triggered')) |int(0) ) > 900 }}"
action:
  - service: light.turn_on
    data:
      entity_id: light.downstairs_hallway
      brightness_pct: 100
