alias: 'Heidi Nightstand Failsafe Off'
initial_state: True
trigger:
  platform: time
  at: '03:00:00'
action:
  - service: switch.turn_off
    entity_id: switch.heidi_nightstand
  - service: notify.pushbullet
    data:
      message: "Heidi's nightstand failsafe off"
      title: "Heidi's nightstand failsafe off"
