alias: 'Kids Button'
initial_state: true
trigger:
  platform: mqtt
  topic: "zigbee2mqtt/Kid's Button/action"
  payload: "single"
action:
  - service: script.boys_room_ceiling
    data:
      button: "kids_button"
