alias: 'Kids Button'
initial_state: true
trigger:
  platform: mqtt
  topic: "sonoff_bridge/kidsbutton"
  payload: "toggle"
action:
  - service: script.boys_room_ceiling
    data:
      button: kids_button
