alias: Morning
trigger:
  platform: time
  at: '08:30:00'
action:
  - service: switch.turn_off
    entity_id: switch.boys_lamp
  - service: notify.pushbullet
    data:
      message: "Boy's lamp turned off"
      title: "Morning"
