alias: 'Outside Lights Nightime On'
initial_state: true
trigger:
  - platform: sun
    event: sunset
    offset: "-00:30:00"
action:
  - service: switch.turn_on
    target:
      entity_id: switch.in_wall_toggle_switch_qfsw_500s