alias: Ring
initial_state: True
trigger:
  - platform: state
    entity_id: binary_sensor.ring_front_door_ding
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.ring_front_door_motion
    from: 'off'
    to: 'on'
action:
  - service: downloader.download_file
    data_template:
      url: ""
      subdir: ""
      filename: ""
