alias: Ring
initial_state: True
trigger:
  - platform: state
    entity_id: binary_sensor.ring_front_door_ding
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.ring_front_door_motion
    from: 'off'
    to: 'on'
action:
  - delay: '00:01:00'
  - service: downloader.download_file
    data_template:
      url: "{{ states.camera.front_door.attributes.video_url }}"
      filename: "{{ now().year }}{% if now().month < 10 -%} 0{{ now().month }} {%- else -%} {{ now().month }} {%- endif %}{% if now().day < 10 -%} 0{{ now().day }} {%- else -%} {{ now().day }} {%- endif %}_{% if now().hour < 10 -%} 0{{ now().hour }} {%- else -%} {{ now().hour }} {%- endif %}{% if now().minute < 10 -%} 0{{ now().minute }} {%- else -%} {{ now().minute }} {%- endif %}{% if now().second < 10 -%} 0{{ now().second }} {%- else -%} {{ now().second }} {%- endif %}.mpg"
      overwrite: false
