alias: 'Internet Speed Bad'
initial_state: True
trigger:
  platform: template
  value_template: '{{ states.sensor.speedtest_download.state| float < 51 }}'
action:
  - service: notify.gmail
    data:
      title: 'Internet Speed Bad'
      message: 'Download speed below 51Mbit/s'
  - service: notify.pushbullet
    data:
      title: 'Internet Speed Bad'
      message: 'Download speed below 51Mbit/s'
