alias: "SSL certificate update restart"
trigger:
  - platform: event
    event_type: folder_watcher
    event_data:
      event_type: modified
      path:
        - /ssl/fullchain.pem
        - /ssl/privkey.pem
action:
  - service: notify.pushbullet
    data:
      message: "Restarting due to SSL certificate update"
  - service: homeassistant.restart