alias: Temp Set Away
trigger:
  platform: state
  entity_id: group.thermostatdevices
  from: 'home'
  to: 'not_home'
action:
  - service: climate.set_temperature
    data_template:
      temperature: >-
        {% if is_state_attr('climate.sensi', 'operation_mode', 'heat') -%}
          {{ states.climate.sensi.attributes.temperature | int - 3 }}
        {% elif is_state_attr('climate.sensi', 'operation_mode', 'cool') -%}
          {{ states.climate.sensi.attributes.temperature | int + 3 }}
        {%- else -%}
          {{ states.climate.sensi.attributes.temperature | int }}
        {%- endif %}
      target_temp_low: >-
        {% if is_state_attr('climate.sensi', 'operation_mode', 'auto') -%}
          {{ states.climate.sensi.attributes.target_temp_low | int - 3 }}
        {%- else -%}
          {{ states.climate.sensi.attributes.target_temp_low | int(71) }}
        {%- endif %}
      target_temp_high: >-
        {% if is_state_attr('climate.sensi', 'operation_mode', 'auto') -%}
          {{ states.climate.sensi.attributes.target_temp_high | int + 3 }}
        {%- else -%}
          {{ states.climate.sensi.attributes.target_temp_high | int(73) }}
        {%- endif %}
  - service: notify.pushbullet
    data:
      title: 'Thermostat set temp changed due to devices leaving home'
      message: ''
