alias: Temp Set Away
trigger:
  platform: state
  entity_id: group.thermostatdevices
  from: 'home'
  to: 'not_home'
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.sensi
      temperature: >-
        {% if is_state_attr('climate.sensi', 'operation_mode', 'heat') -%}
          {{ state_attr('climate.sensi', 'temperature')|int(71) - 3 }}
        {% elif is_state_attr('climate.sensi', 'operation_mode', 'cool') -%}
          {{ state_attr('climate.sensi', 'temperature')|int(73) + 3 }}
        {%- else -%}
          {{ state_attr('climate.sensi', 'temperature')|int(73) }}
        {%- endif %}
      target_temp_low: >-
        {% if is_state_attr('climate.sensi', 'operation_mode', 'auto') -%}
          {{ state_attr('climate.sensi', 'target_temp_low')|int(71) - 3 }}
        {%- else -%}
          {{ state_attr('climate.sensi', 'target_temp_low')|int(71) }}
        {%- endif %}
      target_temp_high: >-
        {% if is_state_attr('climate.sensi', 'operation_mode', 'auto') -%}
          {{ state_attr('climate.sensi', 'target_temp_high')|int(73) + 3 }}
        {%- else -%}
         {{ state_attr('climate.sensi', 'target_temp_low')|int(73) }}
        {%- endif %}
  - service: notify.pushbullet
    data:
      title: 'Thermostat set temp changed due to devices leaving home'
      message: ''
