substitutions:
  name: living-room-bluetooth-proxy
  friendly_name: Living Room Bluetooth Proxy
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret api_key

logger:
  #level: VERY_VERBOSE
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32:
  board: esp32dev
  framework:
    type: esp-idf

#web_server:
#  port: 80

esp32_ble_tracker:
  scan_parameters:
    active: true
  on_ble_advertise:
    - then:

bluetooth_proxy:
  active: true

binary_sensor:
  - platform: ble_presence
    name: !secret phone1_name
    ibeacon_uuid: !secret phone1_uuid
    timeout: 30s